######################################################################
# match unison exactly

resolver: lts-14.7
allow-newer: true # See Unison's stack.yaml
extra-deps:
  - git: git@github.com:jaredly/unison.git
    commit: '03a5c48cca237f9c9045b3f3ac1f6b7c3d3d4f21'
    subdirs:
      - yaks/easytest
      - parser-typechecker
      - yaks/haskeline
      - unison-core

  - base58-bytestring-0.1.0
  - relation-0.2.1
  - shellmet-0.0.1
  - filepattern-0.1.1
  - strings-1.1@sha256:0285dec4c8ab262359342b3e5ef1eb567074669461b9b38404f1cb870c881c5c
  - guid-0.1.0@sha256:a7c975be473f6f142d5cc1b39bc807a99043d20b1bb0873fdfe7a3ce84d2faf1
  - fsutils-0.1.2@sha256:fb3eb68e03e4317352032642d3ed18c796c30f5a3bec40caef69cee0b859df5e
  - prelude-extras-0.4.0.3@sha256:1c10b0123ea13a6423d74a8fcbaeb2d5249b472588abde418a36b47b7c4f48c8
  - sandi-0.5@sha256:b278d072ca717706ea38f9bd646e023f7f2576a778fb43565b434f93638849aa
  - megaparsec-6.5.0

  ######################################################################
  # additional deps

  # The latest
  - git: git@github.com:pkamenarsky/concur-replica
    commit: '0bcf622fce055be4cdc3793ef73a16e227384817'

  # The latest:
  - git: git@github.com:pkamenarsky/replica
    commit: 'db4af3572705bb20222fff1203a1eea3ca5cd542'

  # From concur-replica's stack.yaml. Jun 26, 2019
  - git: git@github.com:ajnsit/concur
    commit: '6c6bcc07b2688182945b28f154a013eee3f624c5'
    subdirs:
      - concur-core
